Project.create!([
  {
    name: "Contabilidad",
    short_name: "Conta",
    code_name: "Mayhem-Accounting",
    creation_date: "2013-01-23",
    release_date: "2013-08-29",
    description: "El sistema de contabilidad es un Engine de Rails montado sobre Mayhem, soporta actualmente 3 tipos de documentos: Catálogos de cuentas, Balanzas y Pólizas.",
    subsystems: "Mercurio, Emisión",
    last_release_date: "2014-12-24",
    last_release_time: "23:35",
    last_release_version: "1.0.0",
    last_release_description: "A lot of features, I don't remember anything you know?",
    last_release_deployer: "Vincent Gutiérrez",
    next_release_date: "2015-05-10",
    next_release_time: "20:00",
    next_release_version: "1.2.0",
    next_release_description: "A lot of fixes I prefer not to list everything here is a shame to me.",
    next_release_deployer:"Oscar Wild"
  },
  {
    name: "Mayhem/Certificados",
    short_name: "CSDS",
    code_name: "Mayhem-Certificates",
    creation_date: "2013-01-23",
    release_date: "2013-08-29",
    description: "El sistema de certificados es un Engine de Rails montado sobre Mayhem, actualmente puedes subir CSD (Certificado de Sello Digitales) y listarlos, sin embargo sólo puedes tener uno activo dentro del sistema.",
    subsystems: "Emisión",
    last_release_date: "2014-12-24",
    last_release_time: "23:35",
    last_release_version: "1.0.0",
    last_release_description: "A lot of features, I don't remember anything you know?",
    last_release_deployer: "Josh Lones",
    next_release_date: "2015-05-10",
    next_release_time: "20:00",
    next_release_version: "1.2.0",
    next_release_description: "A lot of fixes I prefer not to list everything here is a shame to me.",
    next_release_deployer:"Oscar Wild"
  },
  {
    name: "Mayhem/Seguridad",
    short_name: "SEC",
    code_name: "Mayhem-Security",
    creation_date: "2013-01-23",
    release_date: "2013-08-29",
    description: "Sistema de seguridad de mayhem, es un Engine de Rails y está montado sobre Mayhem, permite a través de la interfaz web el login, logout, reinicio de contraseña olvidada, por medio de sistema a sistema soporta la creación de usuarios y clientes, así como su asociación y edición.",
    subsystems: "NA",
    last_release_date: "2014-12-24",
    last_release_time: "23:35",
    last_release_version: "1.0.0",
    last_release_description: "A lot of features, I don't remember anything you know?",
    last_release_deployer: "Vincent Gutiérrez",
    next_release_date: "2015-05-10",
    next_release_time: "20:00",
    next_release_version: "1.2.0",
    next_release_description: "A lot of fixes I prefer not to list everything here is a shame to me.",
    next_release_deployer:"Oscar Wild"
  },
  {
    name: "Mayhem/PR",
    short_name: "PR",
    code_name: "Mayhem-PSRDD",
    creation_date: "2013-01-23",
    release_date: nil,
    description: "Sistema para PRESTADOR DE SERVICIOS DIGITALES, es un engine que está montado sobre Mayhem, el cual soportará en un inicio el documento DPIVA (Declaración de Proveedores IVA), sin embargo está diseñado para soportar los documentos futuros que vaya liberando el SAT de una manera ágil.",
    subsystems: "Hades, Cerberus, TBA ",
    last_release_date: "2014-12-24",
    last_release_time: "23:35",
    last_release_version: "1.0.0",
    last_release_description: "A lot of features, I don't remember anything you know?",
    last_release_deployer: "José A. Dulanto",
    next_release_date: nil,
    next_release_time: "20:00",
    next_release_version: "1.2.0",
    next_release_description: "A lot of fixes I prefer not to list everything here is a shame to me.",
    next_release_deployer:"Oscar Wild"
  },
  {
    name: "Lowes",
    short_name: "MONACO",
    code_name: "Lowes",
    creation_date: "2013-01-23",
    release_date: nil,
    description: "",
    subsystems: "Apollo ver 1.2.3",
    last_release_date: "2014-12-24",
    last_release_time: "23:35",
    last_release_version: "1.0.0",
    last_release_description: "A lot of features, I don't remember anything you know?",
    last_release_deployer: "Josh Lones",
    next_release_date: nil,
    next_release_time: "20:00",
    next_release_version: "1.2.0",
    next_release_description: "A lot of fixes I prefer not to list everything here is a shame to me.",
    next_release_deployer:"Oscar Wild"
  },
  {
    name: "ACN",
    short_name: "ACN",
    code_name: "ACN",
    creation_date: "2013-01-23",
    release_date: nil,
    description: "Accountin is a secret project for a secret agency. Nuff said. Go away.",
    subsystems: "Apollo ver 1.2.3",
    last_release_date: "2014-12-24",
    last_release_time: "23:35",
    last_release_version: "1.0.0",
    last_release_description: "A lot of features, I don't remember anything you know?",
    last_release_deployer: "Josh Lones",
    next_release_date: nil,
    next_release_time: "20:00",
    next_release_version: "1.2.0",
    next_release_description: "A lot of fixes I prefer not to list everything here is a shame to me.",
    next_release_deployer:"Oscar Wild"
  },
  {
    name: "Colabora Genérico",
    short_name: "colabora",
    code_name: "colabora",
    creation_date: "2013-01-23",
    release_date: nil,
    description: "Accountin is a secret project for a secret agency. Nuff said. Go away.",
    subsystems: "Apollo ver 1.2.3",
    last_release_date: "2014-12-24",
    last_release_time: "23:35",
    last_release_version: "1.0.0",
    last_release_description: "A lot of features, I don't remember anything you know?",
    last_release_deployer: "Josh Lones",
    next_release_date: nil,
    next_release_time: "20:00",
    next_release_version: "1.2.0",
    next_release_description: "A lot of fixes I prefer not to list everything here is a shame to me.",
    next_release_deployer:"Oscar Wild"
  },
  {
    name: "Nómina Fiscal",
    short_name: "NF",
    code_name: "nomina",
    creation_date: "2013-01-23",
    release_date: nil,
    description: "Accountin is a secret project for a secret agency. Nuff said. Go away.",
    subsystems: "Apollo ver 1.2.3",
    last_release_date: "2014-12-24",
    last_release_time: "23:35",
    last_release_version: "1.0.0",
    last_release_description: "A lot of features, I don't remember anything you know?",
    last_release_deployer: "Josh Lones",
    next_release_date: nil,
    next_release_time: "20:00",
    next_release_version: "1.2.0",
    next_release_description: "A lot of fixes I prefer not to list everything here is a shame to me.",
    next_release_deployer:"Oscar Wild"
  }
])
